version: '3'

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    hostname: ntfy.${DOMAIN_NAME}
    command:
      - serve
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file: .env
    environment:
      - NTFY_BASE_URL=https://ntfy.${DOMAIN_NAME}
    labels:
      - com.centurylabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.ntfy.entrypoints=https
      - traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAIN_NAME:?error}`)
      - traefik.http.routers.ntfy.service=ntfy
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=cloudflare
      - traefik.http.services.ntfy.loadbalancer.server.port=80
      - traefik.http.routers.ntfy.middlewares=default@file
    expose:
      - 80
    networks:
      - traefik
    volumes:
      - ./cache/:/var/cache/ntfy/
      - ./files/server.yml:/etc/ntfy/server.yml
      - ./files/user.db:/var/lib/ntfy/user.db
      - /etc/localtime:/etc/localtime:ro

networks:
  traefik:
    external: true
    name: traefik