services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      NTFY_BASE_URL: https://ntfy.${TRAEFIK_DOMAIN:?}
    labels:
      - com.centurylabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.ntfy.entrypoints=https
      - traefik.http.routers.ntfy.rule=Host(`ntfy.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=cloudflare
      - traefik.http.services.ntfy.loadbalancer.server.port=80
      - traefik.http.routers.ntfy.middlewares=default@file
    networks:
      - traefik
    volumes:
      - ./cache/:/var/cache/ntfy/
      - ./files/server.yml:/etc/ntfy/server.yml
      - ./data/user.db:/var/lib/ntfy/user.db
      - /etc/localtime:/etc/localtime:ro

networks:
  traefik:
    external: true